### PR TITLE
Upgrade kubernetes client

### LINKED ISSUE #54: Pipelines only run in default namespace
Known issue, but opening here to discuss and track.

https://github.com/fabric8io/openshift-jenkins-s2i-config#todo

In a real deployment, only cluster admins would have access to this namespace. Even for demos, other stuff like the router and registry show up, which you don't want.

/cc @bparees @jimmidyson @fabianofranz

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #54

### CODE REVIEW

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
Sorry craziness with the Jenkins PR merge builder - Github API is flaking a lot atm...

**Comment by bparees** [comment]
@jimmidyson 
1) when is the on-disk project name used now?  when the config field value is empty?
2) can we get this updated plugin pushed into the https://github.com/fabric8io/openshift-jenkins-s2i-config repo?

**Comment by jimmidyson** [comment]
> when is the on-disk project name used now? when the config field value is empty?

Yes
>  can we get this updated plugin pushed into the https://github.com/fabric8io/openshift-jenkins-s2i-config repo?

Updated

**Pull request merged**
