### PR TITLE
Switch to patch for updates

### LINKED ISSUE #71: Build is broken
Seems the build is broken; depending upon a SNAPSHOT dependency:

```
[ERROR] Failed to execute goal on project openshift-jenkins-sync-plugin: Could not resolve dependencies for project io.fabric8:openshift-jenkins-sync-plugin:hpi:0.1-SNAPSHOT: Could not find artifact io.fabric8:kubernetes-model:jar:1.0.44-SNAPSHOT in repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/) -> [Help 1]
```

When setting this locally to `io.fabric8:kubernetes-model:jar:1.0.44` I see a compilation error:

```
ERROR] /home/alr/business/jboss/git/fabric8io/openshift-jenkins-sync-plugin/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMapper.java:[29,38] cannot find symbol
[ERROR] symbol:   class JenkinsPipelineBuildStrategy
[ERROR] location: package io.fabric8.openshift.api.model
```

Dependency of my working on #56

### PR DESCRIPTION
**Pull request by jimmidyson**
Potential fix for #58, fix for #70 once Origin correctly handles JSON patch keys

Fixes #71

### CODE REVIEW

**Comment by sspeiche** [comment]
@jimmidyson there a PR for the origin JSON patch keys?

**Comment by jimmidyson** [comment]
@sspeiche Was waiting on PR to upstream repo to be merged - https://github.com/evanphx/json-patch/pull/27 - before submitting to Kubernetes & Origin.

**Comment by jimmidyson** [comment]
Relevant Origin issue: openshift/origin#7629

**Comment by jimmidyson** [comment]
[merge]

**Comment by spadgett** [comment]
> Potential fix for #58

@jimmidyson The stack trace for number #58 is always an EOFException reading from a websocket. Looks like a different cause?

**Comment by jimmidyson** [comment]
Because it pulls in later version of kubernetes client that also includes some reconnection fixes :)

**Comment by spadgett** [comment]
Ah thanks, makes sense

**Pull request merged**
