### PR TITLE
Use internal API for pipeline state

### LINKED ISSUE #46: missing read permissions in build status message
my build (which is now in the running state, as I would expect), shows this annotation on the build object itself:

 "openshift.io/jenkins-status-json": "\u003chtml\u003e\u003chead\u003e\u003cmeta http-equiv='refresh' content='1;url=/login?from=%2Fjenkins%2Fjob%2Fruby-sample-build%2F1%2Fwfapi%2Fdescribe'/\u003e\u003cscript\u003ewindow.location.replace('/login?from=%2Fjenkins%2Fjob%2Fruby-sample-build%2F1%2Fwfapi%2Fdescribe');\u003c/script\u003e\u003c/head\u003e\u003cbody style='background-color:white; color:white;'\u003e\n\n\nAuthentication required\n\u003c!--\nYou are authenticated as: anonymous\nGroups that you are in:\n  \nPermission you need to have (but didn't): hudson.model.Hudson.Read\n ... which is implied by: hudson.security.Permission.GenericRead\n ... which is implied by: hudson.model.Hudson.Administer\n--\u003e\n\n\u003c/body\u003e\u003c/html\u003e

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #46

### CODE REVIEW

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
[merge]

**Comment by bparees** [comment]
@jimmidyson are you going to build a new snapshot and put it in the https://github.com/rawlingsj/openshift-jenkins-s2i-config repo?

**Comment by jimmidyson** [comment]
Of course ;) I may even test it before I push it.

**Comment by jimmidyson** [comment]
@bparees Ready to go.

**Pull request merged**
