### PR TITLE
Upgrade Jenkins Pipeline REST API plugin

### PR DESCRIPTION
**Pull request by jimmidyson**
@spadgett This should now give you proper stages in the build status annotation.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Fixes #48

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
[merge]

**Comment by fabianofranz** [comment]
Appreciate if you can update it in https://github.com/rawlingsj/openshift-jenkins-s2i-config too, thanks!

**Comment by jimmidyson** [comment]
@fabianofranz We're using https://github.com/fabric8io/openshift-jenkins-s2i-config now - not sure why it was forked rather than transferred. Already updated there.

**Comment by fabianofranz** [comment]
@jimmidyson great, thanks!

**Comment by spadgett** [comment]
@jimmidyson the binary version of the plugin still needs to be added to https://github.com/fabric8io/openshift-jenkins-s2i-config for us to pick it up, correct?

**Comment by jimmidyson** [comment]
Oh bugger yeah - this is painful til we get a first release out... will update now.

**Comment by spadgett** [comment]
perfect, thanks!

**Comment by jimmidyson** [comment]
Done.

**Comment by spadgett** [comment]
hey @jimmidyson I see it in your fork, but not in fabric8io/openshift-jenkins-s2i-config unless I'm missing it

**Comment by jimmidyson** [comment]
It is now :stuck_out_tongue_winking_eye:

**Pull request merged**
